package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMycars<M extends BaseMycars<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return get("uid");
	}
	
	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return get("uname");
	}

	public void setCarmodel(java.lang.String carmodel) {
		set("carmodel", carmodel);
	}

	public java.lang.String getCarmodel() {
		return get("carmodel");
	}

	public void setLoad(java.lang.String load) {
		set("load", load);
	}

	public java.lang.String getLoad() {
		return get("load");
	}

	public void setCphone(java.lang.String cphone) {
		set("cphone", cphone);
	}

	public java.lang.String getCphone() {
		return get("cphone");
	}

	public void setPlatenum(java.lang.String platenum) {
		set("platenum", platenum);
	}

	public java.lang.String getPlatenum() {
		return get("platenum");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}

}
