package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVersion<M extends BaseVersion<M>> extends Model<M> implements IBean {

	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}

	public java.lang.String getUpdatetime() {
		return get("updatetime");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return get("version");
	}

	public void setAndroidpath(java.lang.String androidpath) {
		set("androidpath", androidpath);
	}

	public java.lang.String getAndroidpath() {
		return get("androidpath");
	}
	
	public void setIospath(java.lang.String iospath) {
		set("iospath", iospath);
	}
	
	public java.lang.String getIospath() {
		return get("iospath");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
