package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrade_cargo<M extends BaseTrade_cargo<M>> extends Model<M> implements IBean {

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}

	public java.lang.String getTid() {
		return get("tid");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCarnum(java.lang.String carnum) {
		set("carnum", carnum);
	}

	public java.lang.String getCarnum() {
		return get("carnum");
	}
	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return get("uname");
	}
	
	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return get("num");
	}

	public void setUphone(java.lang.String uphone) {
		set("uphone", uphone);
	}

	public java.lang.String getUphone() {
		return get("uphone");
	}

	public void setCartype(java.lang.String cartype) {
		set("cartype", cartype);
	}

	public java.lang.String getCartype() {
		return get("cartype");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setTtime(java.lang.String ttime) {
		set("ttime", ttime);
	}

	public java.lang.String getTtime() {
		return get("ttime");
	}

	public void setRmoney(java.lang.String rmoney) {
		set("rmoney", rmoney);
	}
	
	public java.lang.String getRmoney() {
		return get("rmoney");
	}
	
	public void setTypemoney(java.lang.String typemoney) {
		set("typemoney", typemoney);
	}
	
	public java.lang.String getRypemoney() {
		return get("typemoney");
	}
	
	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}
	
	public java.lang.String getImgs() {
		return get("imgs");
	}
}
