package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}

	public void setSid(java.lang.String sid) {
		set("sid", sid);
	}

	public java.lang.String getSid() {
		return get("sid");
	}

	public void setGoodid(java.lang.String goodid) {
		set("goodid", goodid);
	}

	public java.lang.String getGoodid() {
		return get("goodid");
	}

	public void setGname(java.lang.String gname) {
		set("gname", gname);
	}

	public java.lang.String getGname() {
		return get("gname");
	}

	public void setGattr(java.lang.String gattr) {
		set("gattr", gattr);
	}

	public java.lang.String getGattr() {
		return get("gattr");
	}

	public void setGprice(java.lang.String gprice) {
		set("gprice", gprice);
	}

	public java.lang.String getGprice() {
		return get("gprice");
	}

	public void setGnum(java.lang.String gnum) {
		set("gnum", gnum);
	}

	public java.lang.String getGnum() {
		return get("gnum");
	}
	
	public void setGimg(java.lang.String gimg) {
		set("gimg", gimg);
	}
	
	public java.lang.String getGimg() {
		return get("gimg");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return get("status");
	}
	
	public void setAddrid(java.lang.String addrid) {
		set("addrid", addrid);
	}
	
	public java.lang.String getAddrid() {
		return get("addrid");
	}

	public void setConmen(java.lang.String conmen) {
		set("conmen", conmen);
	}
	
	public java.lang.String getConmen() {
		return get("conmen");
	}
	public void setGtype(java.lang.String gtype) {
		set("gtype", gtype);
	}
	
	public java.lang.String getGtype() {
		return get("gtype");
	}
	public void setPricetype(java.lang.String pricetype) {
		set("pricetype", pricetype);
	}
	
	public java.lang.String getPricetype() {
		return get("pricetype");
	}

}
