package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrade_car<M extends BaseTrade_car<M>> extends Model<M> implements IBean {

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}

	public java.lang.String getTid() {
		return get("tid");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return get("status");
	}

	public void setStartadd(java.lang.String startadd) {
		set("startadd", startadd);
	}

	public java.lang.String getStartadd() {
		return get("startadd");
	}

	public void setTargetadd(java.lang.String targetadd) {
		set("targetadd", targetadd);
	}

	public java.lang.String getTargetadd() {
		return get("targetadd");
	}
	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return get("uname");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setDunwei(java.lang.String dunwei) {
		set("dunwei", dunwei);
	}

	public java.lang.String getDunwei() {
		return get("dunwei");
	}

	public void setTtime(java.lang.String ttime) {
		set("ttime", ttime);
	}

	public java.lang.String getTtime() {
		return get("ttime");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}
	
	public java.lang.String getImgs() {
		return get("imgs");
	}
}
