package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePostcomment<M extends BasePostcomment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}

	public java.lang.String getPid() {
		return get("pid");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}
	
	public void setReplay(java.lang.String replay) {
		set("replay", replay);
	}
	
	public java.lang.String getReplay() {
		return get("replay");
	}
	
	public void setMsgid(java.lang.String msgid) {
		set("msgid", msgid);
	}
	
	public java.lang.String getMsgid() {
		return get("msgid");
	}
	
	public void setIfnew(java.lang.String ifnew) {
		set("ifnew", ifnew);
	}
	
	public java.lang.String getIfnew() {
		return get("ifnew");
	}

}
