package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setGoodid(java.lang.String goodid) {
		set("goodid", goodid);
	}

	public java.lang.String getGoodid() {
		return get("goodid");
	}

	public void setGname(java.lang.String gname) {
		set("gname", gname);
	}

	public java.lang.String getGname() {
		return get("gname");
	}

	public void setGbrand(java.lang.String gbrand) {
		set("gbrand", gbrand);
	}

	public java.lang.String getGbrand() {
		return get("gbrand");
	}

	public void setGmodel(java.lang.String gmodel) {
		set("gmodel", gmodel);
	}

	public java.lang.String getGmodel() {
		return get("gmodel");
	}

	public void setGprice(java.lang.String gprice) {
		set("gprice", gprice);
	}

	public java.lang.String getGprice() {
		return get("gprice");
	}

	public void setGtype(java.lang.String gtype) {
		set("gtype", gtype);
	}

	public java.lang.String getGtype() {
		return get("gtype");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setGattrnums(java.lang.String gattrnums) {
		set("gattrnums", gattrnums);
	}

	public java.lang.String getGattrnums() {
		return get("gattrnums");
	}

	public void setGpictures(java.lang.String gpictures) {
		set("gpictures", gpictures);
	}

	public java.lang.String getGpictures() {
		return get("gpictures");
	}

	public void setGparams(java.lang.String gparams) {
		set("gparams", gparams);
	}

	public java.lang.String getGparams() {
		return get("gparams");
	}

	public void setGtotalnum(java.lang.String gtotalnum) {
		set("gtotalnum", gtotalnum);
	}

	public java.lang.String getGtotalnum() {
		return get("gtotalnum");
	}

	public void setGsailnum(java.lang.String gsailnum) {
		set("gsailnum", gsailnum);
	}

	public java.lang.String getGsailnum() {
		return get("gsailnum");
	}

	public void setDiscount(java.lang.String discount) {
		set("discount", discount);
	}

	public java.lang.String getDiscount() {
		return get("discount");
	}

	public void setStoreid(java.lang.String storeid) {
		set("storeid", storeid);
	}

	public java.lang.String getStoreid() {
		return get("storeid");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}
	
	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}
	
	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setGvp1(java.lang.String gvp1) {
		set("gvp1", gvp1);
	}
	
	public java.lang.String getGvp1() {
		return get("gvp1");
	}
	
	public void setGvp2(java.lang.String gvp2) {
		set("gvp2", gvp2);
	}
	
	public java.lang.String getGvp2() {
		return get("gvp2");
	}
	public void setGvp3(java.lang.String gvp3) {
		set("gvp3", gvp3);
	}
	
	public java.lang.String getGvp3() {
		return get("gvp3");
	}
	public void setQvp1(java.lang.String qvp1) {
		set("qvp1", qvp1);
	}
	
	public java.lang.String getQvp1() {
		return get("qvp1");
	}
	
	public void setQvp2(java.lang.String qvp2) {
		set("qvp2", qvp2);
	}
	
	public java.lang.String getQvp2() {
		return get("qvp2");
	}
	
	public void setQvp3(java.lang.String qvp3) {
		set("qvp3", qvp3);
	}
	
	public java.lang.String getQvp3() {
		return get("qvp3");
	}
	

	
}
