package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYuyue<M extends BaseYuyue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCard(java.lang.String card) {
		set("card", card);
	}

	public java.lang.String getCard() {
		return get("card");
	}

	public void setModels(java.lang.String models) {
		set("models", models);
	}

	public java.lang.String getModels() {
		return get("models");
	}

	public void setPolicy(java.lang.String policy) {
		set("policy", policy);
	}

	public java.lang.String getPolicy() {
		return get("policy");
	}

	public void setLicense(java.lang.String license) {
		set("license", license);
	}

	public java.lang.String getLicense() {
		return get("license");
	}

	public void setDamaged(java.lang.String damaged) {
		set("damaged", damaged);
	}

	public java.lang.String getDamaged() {
		return get("damaged");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}

	public void setGgerid(java.lang.String ggerid) {
		set("ggerid", ggerid);
	}

	public java.lang.String getGgerid() {
		return get("ggerid");
	}

	public void setService(java.lang.String service) {
		set("service", service);
	}

	public java.lang.String getService() {
		return get("service");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}
	
	public void setSid(java.lang.String sid) {
		set("sid", sid);
	}

	public java.lang.String getSid() {
		return get("sid");
	}
	public void setW_type(java.lang.String w_type) {
	set("w_type", w_type);
	}
	public java.lang.String getW_type() {
	return get("w_type");
	}
	
	public void setNstore(java.lang.String nstore) {
		set("nstore", nstore);
		}
		public java.lang.String getNstore() {
		return get("nstore");
	}
	public void setReconment(java.lang.String reconment) {
		set("reconment", reconment);
	}
	
	public java.lang.String getReconment() {
		return get("reconment");
	}
	public void setConmen(java.lang.String conmen) {
		set("conmen", conmen);
	}
	
	public java.lang.String getConmen() {
		return get("conmen");
	}
	public void setPricetype(java.lang.String pricetype) {
		set("pricetype", pricetype);
	}
	
	public java.lang.String getPricetype() {
		return get("pricetype");
	}
	public void setReplay(java.lang.String replay) {
		set("replay", replay);
	}
	
	public java.lang.String getReplay() {
		return get("replay");
	}
	public void setGnum(java.lang.String gnum) {
		set("gnum", gnum);
	}
	
	public java.lang.String getGnum() {
		return get("gnum");
	}
	public void setDriver(java.lang.String driver) {
		set("driver", driver);
	}
	
	public java.lang.String getDriver() {
		return get("driver");
	}

}
