package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	public void setCartid(java.lang.String cartid) {
		set("cartid", cartid);
	}

	public java.lang.String getCartid() {
		return get("cartid");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}

	public void setSname(java.lang.String sname) {
		set("sname", sname);
	}

	public java.lang.String getSname() {
		return get("sname");
	}

	public void setGname(java.lang.String gname) {
		set("gname", gname);
	}

	public java.lang.String getGname() {
		return get("gname");
	}

	public void setGattr(java.lang.String gattr) {
		set("gattr", gattr);
	}

	public java.lang.String getGattr() {
		return get("gattr");
	}

	public void setGimg(java.lang.String gimg) {
		set("gimg", gimg);
	}

	public java.lang.String getGimg() {
		return get("gimg");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}

	public java.lang.String getNum() {
		return get("num");
	}

	public void setDiscount(java.lang.String discount) {
		set("discount", discount);
	}

	public java.lang.String getDiscount() {
		return get("discount");
	}

	public void setIspay(java.lang.String ispay) {
		set("ispay", ispay);
	}

	public java.lang.String getIspay() {
		return get("ispay");
	}

	public void setSid(java.lang.String sid) {
		set("sid", sid);
	}

	public java.lang.String getSid() {
		return get("sid");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}

	public void setGoodid(java.lang.String goodid) {
		set("goodid", goodid);
	}

	public java.lang.String getGoodid() {
		return get("goodid");
	}

	public void setGtype(java.lang.String gtype) {
		set("gtype", gtype);
	}

	public java.lang.String getGtype() {
		return get("gtype");
	}

}
