package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGger<M extends BaseGger<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setHeadimg(java.lang.String headimg) {
		set("headimg", headimg);
	}

	public java.lang.String getHeadimg() {
		return get("headimg");
	}

	public void setEdu(java.lang.String edu) {
		set("edu", edu);
	}

	public java.lang.String getEdu() {
		return get("edu");
	}

	public void setWorkyear(java.lang.String workyear) {
		set("workyear", workyear);
	}

	public java.lang.String getWorkyear() {
		return get("workyear");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	public java.lang.String getDomain() {
		return get("domain");
	}

	public void setServiceid(java.lang.String serviceid) {
		set("serviceid", serviceid);
	}

	public java.lang.String getServiceid() {
		return get("serviceid");
	}

}
