package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarsell<M extends BaseCarsell<M>> extends Model<M> implements IBean {

	public void setCarsellid(java.lang.String carsellid) {
		set("carsellid", carsellid);
	}

	public java.lang.String getCarsellid() {
		return get("carsellid");
	}

	public void setInformation(java.lang.String information) {
		set("information", information);
	}

	public java.lang.String getInformation() {
		return get("information");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setArchives(java.lang.String archives) {
		set("archives", archives);
	}

	public java.lang.String getArchives() {
		return get("archives");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setSell(java.lang.String sell) {
		set("sell", sell);
	}

	public java.lang.String getSell() {
		return get("sell");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setPricenew(java.lang.String pricenew) {
		set("pricenew", pricenew);
	}

	public java.lang.String getPricenew() {
		return get("pricenew");
	}

	public void setBargain(java.lang.String bargain) {
		set("bargain", bargain);
	}

	public java.lang.String getBargain() {
		return get("bargain");
	}

	public void setTransfer(java.lang.String transfer) {
		set("transfer", transfer);
	}

	public java.lang.String getTransfer() {
		return get("transfer");
	}

}
