package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTypes<M extends BaseTypes<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setStype(java.lang.String stype) {
		set("stype", stype);
	}

	public java.lang.String getStype() {
		return get("stype");
	}

	public void setTname(java.lang.String tname) {
		set("tname", tname);
	}

	public java.lang.String getTname() {
		return get("tname");
	}

	public void setFid(java.lang.String fid) {
		set("fid", fid);
	}

	public java.lang.String getFid() {
		return get("fid");
	}
	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

}
