package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSale<M extends BaseSale<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setSid(java.lang.String sid) {
		set("sid", sid);
	}

	public java.lang.String getSid() {
		return get("sid");
	}

	public void setGname(java.lang.String gname) {
		set("gname", gname);
	}

	public java.lang.String getGname() {
		return get("gname");
	}

	public void setNums(java.lang.String nums) {
		set("nums", nums);
	}

	public java.lang.String getNums() {
		return get("nums");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setStarttime(java.lang.String starttime) {
		set("starttime", starttime);
	}

	public java.lang.String getStarttime() {
		return get("starttime");
	}

	public void setEndtime(java.lang.String endtime) {
		set("endtime", endtime);
	}

	public java.lang.String getEndtime() {
		return get("endtime");
	}

}
