package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}

	public java.lang.String getCname() {
		return get("cname");
	}

	public void setCtype(java.lang.String ctype) {
		set("ctype", ctype);
	}

	public java.lang.String getCtype() {
		return get("ctype");
	}

	public void setCimg(java.lang.String cimg) {
		set("cimg", cimg);
	}

	public java.lang.String getCimg() {
		return get("cimg");
	}

	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

	public java.lang.String getIdentity() {
		return get("identity");
	}

	public void setCinfo(java.lang.String cinfo) {
		set("cinfo", cinfo);
	}

	public java.lang.String getCinfo() {
		return get("cinfo");
	}

	public void setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
	}

	public java.lang.String getCstatus() {
		return get("cstatus");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return get("uid");
	}

}
