package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setUtype(java.lang.String utype) {
		set("utype", utype);
	}

	public java.lang.String getUtype() {
		return get("utype");
	}

	public void setPoints(java.lang.String points) {
		set("points", points);
	}

	public java.lang.String getPoints() {
		return get("points");
	}

	public void setMoney(java.lang.String money) {
		set("money", money);
	}

	public java.lang.String getMoney() {
		return get("money");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setIfpfct(java.lang.String ifpfct) {
		set("ifpfct", ifpfct);
	}

	public java.lang.String getIfpfct() {
		return get("ifpfct");
	}

	public void setPaypwd(java.lang.String paypwd) {
		set("paypwd", paypwd);
	}

	public java.lang.String getPaypwd() {
		return get("paypwd");
	}
	
	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}
	
	public java.lang.String getCrttime() {
		return get("crttime");
	}

}
