package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGogo<M extends BaseGogo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLoss(java.lang.String loss) {
		set("loss", loss);
	}

	public java.lang.String getLoss() {
		return get("loss");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setStoreid(java.lang.String storeid) {
		set("storeid", storeid);
	}

	public java.lang.String getStoreid() {
		return get("storeid");
	}
	public void setInclod(java.lang.String inclod) {
		set("inclod", inclod);
	}
	
	public java.lang.String getInclod() {
		return get("inclod");
	}

}
