package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCargo<M extends BaseCargo<M>> extends Model<M> implements IBean {

	public void setCgid(java.lang.String cgid) {
		set("cgid", cgid);
	}

	public java.lang.String getCgid() {
		return get("cgid");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return get("uid");
	}
	
	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return get("uname");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}

	public java.lang.String getCtime() {
		return get("ctime");
	}

	public void setStartadd(java.lang.String startadd) {
		set("startadd", startadd);
	}

	public java.lang.String getStartadd() {
		return get("startadd");
	}

	public void setTargetadd(java.lang.String targetadd) {
		set("targetadd", targetadd);
	}

	public java.lang.String getTargetadd() {
		return get("targetadd");
	}

	public void setCinfo(java.lang.String cinfo) {
		set("cinfo", cinfo);
	}

	public java.lang.String getCinfo() {
		return get("cinfo");
	}
	
	public void setPrice(java.lang.String price) {
		set("price", price);
	}
	
	public java.lang.String getPrice() {
		return get("price");
	}

	public void setCrequire(java.lang.String crequire) {
		set("crequire", crequire);
	}

	public java.lang.String getCrequire() {
		return get("crequire");
	}

	public void setCnote(java.lang.String cnote) {
		set("cnote", cnote);
	}

	public java.lang.String getCnote() {
		return get("cnote");
	}

	public void setCphone(java.lang.String cphone) {
		set("cphone", cphone);
	}

	public java.lang.String getCphone() {
		return get("cphone");
	}

	public void setCrttime(java.lang.String crttime) {
		set("crttime", crttime);
	}

	public java.lang.String getCrttime() {
		return get("crttime");
	}
	
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	public java.lang.String getResult() {
		return get("result");
	}
	
	public void setRname(java.lang.String rname) {
		set("rname", rname);
	}
	
	public java.lang.String getRname() {
		return get("rname");
	}
}
