package com.demo.common.model;

import com.demo.common.model.base.BaseCargo;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cargo extends BaseCargo<Cargo> {
	public static final Cargo dao = new Cargo();
	
	public Page<Cargo> getHwsPaginate(int pageNumber, int pageSize, String qidian, String zhongdian, String ctype, String jiage) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}
		String N = jiage;   
		String L="";   
		String R="";   
		int k= N.length();   
		for (int i = 0; i < N.length(); i++){   
			if (N.substring(i, i + 1).equals("|")){     
				L=N.substring(0,i).trim();   
				R=N.substring(i+1,k).trim();   
			}
		}
//		String L = "", R = "";
		StringBuilder sql = new StringBuilder();
		sql.append(" from t_cargo where 1=1 and result = 0  ");
		if (!StringUtils.isEmptyOrWhitespaceOnly(qidian)) {
			sql.append(" and startadd like '%" + qidian + "%'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(zhongdian)) {
			sql.append(" and targetadd like '%" + zhongdian + "%'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(ctype)) {
			sql.append(" and crequire like '%" + ctype + "%'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(jiage)) {
			L = jiage.split("~")[0];
			R = jiage.split("~")[1];
			sql.append(" and price between "+L+" AND "+R+"");
		}
		sql.append(" order by crttime desc");
		System.out.println(sql.toString());
		Page<Cargo> page = Cargo.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;
	}

	public Page<Cargo> getHwsP(int pageNumber, int pageSize, String uid) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}
		String sql = "select * from t_cargo where uid = '"+uid+"' order by crttime desc ";
		Page<Cargo> page = Cargo.dao.paginate(pageNumber, pageSize, sql);
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;
	}
}
