package com.demo.common.model;

import com.demo.common.model.base.BaseCarpre;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carpre extends BaseCarpre<Carpre> {
	public static final Carpre dao = new Carpre();
}
