package com.demo.common.model;

import com.demo.common.model.base.BaseCars;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cars extends BaseCars<Cars> {
	public static final Cars dao = new Cars();
	
	public Page<Cars> getCarsPaginate(int pageNumber, int pageSize, String qidian, String zhongdian, String ctype, String dunwei) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_cars t left join t_user f on t.uid=f.userid where 1=1 and t.result = 0 ");
		if (!StringUtils.isEmptyOrWhitespaceOnly(qidian)) {
			sql.append(" and t.startadd like '%" + qidian + "%'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(zhongdian)) {
			sql.append(" and t.targetadd like '%" + zhongdian + "%'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(ctype)) {
			sql.append(" and t.carmodel = '" + ctype + "'");
		}
		if (!StringUtils.isEmptyOrWhitespaceOnly(dunwei)) {
			sql.append(" and t.load < " + dunwei + " ");
		}
		sql.append(" order by crttime desc ");
		Page<Cars> page = Cars.dao.paginate(pageNumber, pageSize, "select t.*,f.points,f.userid", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;
	}

	public Page<Cars> getCarsP(int pageNumber, int pageSize, String uid) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}
		String sql = "select t.*,f.points from t_cars t left join t_user f on t.uid=f.userid where t.uid = '"+uid+"' order by crttime desc ";
		Page<Cars> page = Cars.dao.paginate(pageNumber, pageSize, sql);
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;

	}
}
