package com.demo.common.model;

import com.demo.common.model.base.BaseCarsell;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carsell extends BaseCarsell<Carsell> {
	public static final Carsell dao = new Carsell();

	public Page<Carsell> getStoreAllpage(int pageNum, int pageSize, String conmentQM, String orderCondQM, String brand) {
		if (pageNum < 1) {
			pageNum = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_carsell where type = 'xc' ");
		if (!StringUtils.isEmptyOrWhitespaceOnly(conmentQM)) {
			sql.append(" and style like '%" + conmentQM + "%'");
		}
//		if (!StringUtils.isEmptyOrWhitespaceOnly(orderCondQM)) {
//			sql.append(" order by "+orderCondQM+"");
//		}
//		if (!StringUtils.isEmptyOrWhitespaceOnly(brand)) {
//			sql.append(" order by "+brand+"");
//		}
		Page<Carsell> page = Carsell.dao.paginate(pageNum, pageSize, "select *", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNum > totalPage) {
			pageNum = totalPage;
		}

		return page;
	}

	public Page<Carsell> getjiucheAllpage(int pageNumber, int pageSize, String conmentES, String orderCondES, String brand) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_carsell where type = 'es' ");
		if (!StringUtils.isEmptyOrWhitespaceOnly(conmentES)) {
			sql.append(" and style like '%" + conmentES + "%'");
		}
//		if (!StringUtils.isEmptyOrWhitespaceOnly(orderCondES)) {
//			sql.append(" order by "+orderCondES+"");
//		}
//		if (!StringUtils.isEmptyOrWhitespaceOnly(brand)) {
//			sql.append(" order by "+brand+"");
//		}
		Page<Carsell> page = Carsell.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;
	}

	public Page<Carsell> searchGoodsPage2(int pageNum, int pageSize, String content, String orderCond) {
		if (pageNum < 1) {
			pageNum = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_carsell  where ");
		if (!StringUtils.isEmptyOrWhitespaceOnly(content)) {
			sql.append("  style like '%"+ content +"%' ");
		}
//		if (!StringUtils.isEmptyOrWhitespaceOnly(orderCond)) {
//			sql.append(" order by "+orderCond+"");
//		}
		Page<Carsell> page = Carsell.dao.paginate(pageNum, pageSize, "select *", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNum > totalPage) {
			pageNum = totalPage;
		}

		return page;
	}
}
