package com.demo.common.model;

import com.demo.common.model.base.BaseCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {
	public static final Cart dao = new Cart();
}
