package com.demo.common.model;

import com.demo.common.model.base.BaseGcomment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gcomment extends BaseGcomment<Gcomment> {
	public static final Gcomment dao = new Gcomment();
}
