package com.demo.common.model;

import com.demo.common.model.base.BaseGger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gger extends BaseGger<Gger> {
	public static final Gger dao = new Gger();
}
