package com.demo.common.model;

import com.demo.common.model.base.BaseLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Login extends BaseLogin<Login> {
	public static final Login dao = new Login();
}
