package com.demo.common.model;

import com.demo.common.model.base.BaseMycars;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mycars extends BaseMycars<Mycars> {
	public static final Mycars dao = new Mycars();
	
}
