package com.demo.common.model;

import com.demo.common.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post();
}
