package com.demo.common.model;

import com.demo.common.model.base.BasePostcomment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Postcomment extends BasePostcomment<Postcomment> {
	public static final Postcomment dao = new Postcomment();
}
