package com.demo.common.model;

import com.demo.common.model.base.BaseSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sale extends BaseSale<Sale> {
	public static final Sale dao = new Sale();
}
