package com.demo.common.model;

import com.demo.common.model.base.BaseStore;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	public static final Store dao = new Store();

	public Page<Store> getStoreLTpage(int pageNumber, int pageSize, String content) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_store where type = 'carLT' ");
		
		if (!StringUtils.isEmptyOrWhitespaceOnly(content)) {
			sql.append(" and sname like '%" + content + "%'");
		}
		

		Page<Store> page = Store.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
		int totalPage = page.getTotalPage();
		if (totalPage < 1) {
			totalPage = 1;
		}
		if (pageNumber > totalPage) {
			pageNumber = totalPage;
		}

		return page;
	}

	public Page<Store> getStorePJpage(int pageNumber, int pageSize, String content) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_store where type = 'carPJ' ");
		
		if (!StringUtils.isEmptyOrWhitespaceOnly(content)) {
			sql.append(" and sname like '%" + content + "%'");
		}
		

		Page<Store> page = Store.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
			int totalPage = page.getTotalPage();
			if (totalPage < 1) {
				totalPage = 1;
			}
			if (pageNumber > totalPage) {
				pageNumber = totalPage;
			}
	
			return page;
	}

	public Page<Store> getStoreJYpage(int pageNumber, int pageSize, String content ) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuilder sql = new StringBuilder();
		sql.append(" from t_store where type = 'carJY' ");
		
		if (!StringUtils.isEmptyOrWhitespaceOnly(content)) {
			sql.append(" and sname like '%"+ content +"%'");
		}
		

		Page<Store> page = Store.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
			int totalPage = page.getTotalPage();
			if (totalPage < 1) {
				totalPage = 1;
			}
			if (pageNumber > totalPage) {
				pageNumber = totalPage;
			}
	
			return page;
	}

	public Page<Store> getStoreAllpage(int pageNumber, int pageSize, String content) {
		if (pageNumber < 1) {
			pageNumber = 1;
		}

		StringBuffer sql = new StringBuffer();
		sql.append(" from t_store where 1=1 ");
		
		if (!StringUtils.isEmptyOrWhitespaceOnly(content)) {
			sql.append(" and sname like '%" + content + "%'");
		}
		

		Page<Store> page = Store.dao.paginate(pageNumber, pageSize, "select *", sql.toString());
			int totalPage = page.getTotalPage();
			if (totalPage < 1) {
				totalPage = 1;
			}
			if (pageNumber > totalPage) {
				pageNumber = totalPage;
			}
	
			return page;
	}
}
