package com.demo.common.model;

import com.demo.common.model.base.BaseSzdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Szdetail extends BaseSzdetail<Szdetail> {
	public static final Szdetail dao = new Szdetail();
}
