package com.demo.common.model;

import com.demo.common.model.base.BaseTrade_car;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trade_car extends BaseTrade_car<Trade_car> {
	public static final Trade_car dao = new Trade_car();
}
