package com.demo.common.model;

import com.demo.common.model.base.BaseTrade_cargo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trade_cargo extends BaseTrade_cargo<Trade_cargo> {
	public static final Trade_cargo dao = new Trade_cargo();
}
