package com.demo.common.model;

import com.demo.common.model.base.BaseTypes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Types extends BaseTypes<Types> {
	public static final Types dao = new Types();
}
