package com.demo.common.model;

import com.demo.common.model.base.BaseVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Version extends BaseVersion<Version> {
	public static final Version dao = new Version();
}
